INTERACTIVE_MODELS_PATH: "../../../../mnt/sda/suhohan/ritm_pth"
EXPS_PATH: "./experiments"

# Evaluation datasets
GRABCUT_PATH: "../../../../mnt/sda/suhohan/GrabCut"
BERKELEY_PATH: "../../../../mnt/sda/suhohan/Berkeley"
DAVIS_PATH: "../../../../mnt/sda/suhohan/DAVIS"
COCO_MVAL_PATH: "../../../../mnt/sda/suhohan/COCO_MVal"

# Train datasets
DATASET_PATH: "../../../../mnt/sda/suhohan/"
BRATS_PATH: "../../../../mnt/sda/suhohan/BraTS2020"
SBD_PATH: "../../../../mnt/sda/suhohan/SBD"
COCO_PATH: "../../../../mnt/sda/suhohan/coco2017"
LVIS_PATH: "../../../../mnt/sda/suhohan/LVIS"
OPENIMAGES_PATH: "../../../../mnt/sda/suhohan/OpenImages"
PASCALVOC_PATH: "../../../../mnt/sda/suhohan/PascalVOC"
ADE20K_PATH: "../../../../mnt/sda/suhohan/ADE20K"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "../../../../mnt/sda/suhohan/hrnet/pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "../../../../mnt/sda/suhohan/hrnet/pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "../../../../mnt/sda/suhohan/hrnet/pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "../../../../mnt/sda/suhohan/hrnet/pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"

# Logs
LOGS_PATH: "./logs"